#!/bin/bash

#provide one work/sentence as an argument to the script. if in that sentence will be an IP address, the script will try to find
# if the IP address is reachable or not

#argument check
if [ $# -ne 1 ]; then
  echo "Provide exactly one argument"
  exit 1
fi

VAR1=$1
#IP address regex
REGEX="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"

#regex check

if ! [[ $VAR1 ~= $REGEX ]]; then
  echo "no IP address provided"
  exit 2
fi

IP=${BASH_REMATCH[0]}

#find if IP address is reachable or not
ping -c1 $IP 1>/dev/null
if [ $? -eq 0 ]; then
  STATUS="ALIVE"
else
  STATUS="UNREACHABLE"
fi

echo "IP found: $IP ($STATUS)"




